name: Auto-Deploy Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Environments
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Dependency Automation
      run: bash scripts/install-tools.sh

    - name: Build & Validate
      run: |
        cd frontend && npm run build && npm run test:ci
        cd ../backend && npm run build && npm run test:ci

    - name: Vercel Deployment
      uses: vercel/vercel-action@v3.0.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: frontend
        auto-alias: true

    - name: Post-Deploy Verification
      run: node -e "require('./version-tracker.js').logDeployment()"
